version: '2.1'
services:
  vibion-eureka-registry:
    build: ./vibion-eureka-registry
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 5s
      timeout: 5s
      retries: 10
  vibion-users:
    build: ./vibion-users
    ports:
      - "8200:8080"
    depends_on:
      vibion-eureka-registry:
        condition: service_healthy
      
  mongo:
    image: "mongo:4.1-bionic"
    volumes:
      - "./data:/data/db"
    env_file:
      - docker_mongo.env