version: '3'
services:
  eureka-registry:
    build: ./vibion-eureka-registry
    ports:
      - "8761:8761"
  users:
    build: ./vibion-users
    ports:
      - "8200:8200"
    depends_on:
      - eureka-registry
  mongo:
    image: "mongo:4.1-bionic"
    volumes:
      - "./data:/data/db"
    env_file:
      - docker_mongo.env